// SPDX-License-Identifier: MPL-2.0
import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Keypair,Account,TransactionBuilder,Networks} from '@stellar/stellar-sdk';import {createAttestation,verifyAttestation,encodeStatus,decodeStatus,buildStatusTransaction,statusKey} from '../src/index.mjs';
const record=JSON.parse(readFileSync(new URL('../examples/record.json',import.meta.url))),key=Keypair.random();const manifest=createAttestation(record,key);const trust={[key.publicKey()]:{enabled:true,manufacturers:['dyness'],schema_versions:['0.1']}};
const lookup=async()=>decodeStatus(encodeStatus(manifest));
test('independent consumer verifies private record without shared storage',async()=>{const r=await verifyAttestation(structuredClone(record),structuredClone(manifest),trust,lookup);assert.equal(r.status,'verified');});
test('canonical object ordering preserves verification',async()=>{const reordered={asset:record.asset,record_id:record.record_id,schema_version:record.schema_version};assert.equal((await verifyAttestation(reordered,manifest,trust,lookup)).status,'verified');});
test('random salts prevent identical records having stable public commitments',()=>{const a=createAttestation(record,key),b=createAttestation(record,key);assert.notEqual(a.id,b.id);assert.notEqual(a.salt,b.salt);assert.notEqual(a.commitment,b.commitment);});
for(const field of ['salt','commitment','id','signature','issuer','network','schema_version'])test('reject altered '+field,async()=>{const m={...manifest,[field]:'tampered'};assert.equal((await verifyAttestation(record,m,trust,lookup)).status,'invalid');});
test('altered evidence fails',async()=>{const d=structuredClone(record);d.asset.serial_number='changed';assert.equal((await verifyAttestation(d,manifest,trust,lookup)).status,'invalid');});
test('unknown and retired issuers fail consumer policy',async()=>{assert.equal((await verifyAttestation(record,manifest,{},lookup)).status,'untrusted_issuer');assert.equal((await verifyAttestation(record,manifest,{[key.publicKey()]:{...trust[key.publicKey()],enabled:false}},lookup)).status,'untrusted_issuer');});
test('manufacturer authority does not follow key ownership alone',async()=>{const t={[key.publicKey()]:{...trust[key.publicKey()],manufacturers:['other']}};assert.equal((await verifyAttestation(record,manifest,t,lookup)).status,'untrusted_issuer');});
test('revoked and superseded are not verified',async()=>{for(const state of ['revoked','superseded']){const next=state==='superseded'?createAttestation(record,key).id:undefined;assert.equal((await verifyAttestation(record,manifest,trust,async()=>decodeStatus(encodeStatus(manifest,state,next)))).status,state);}});
test('missing and unavailable ledger status stays unknown',async()=>{assert.equal((await verifyAttestation(record,manifest,trust,async()=>null)).status,'unknown');assert.equal((await verifyAttestation(record,manifest,trust,async()=>{throw Error('offline');})).status,'unknown');});
test('different ledger commitment fails',async()=>assert.equal((await verifyAttestation(record,manifest,trust,async()=>({state:'active',commitment:'0'.repeat(64)}))).status,'invalid'));
test('public operation contains no record, salt or serial',()=>{const tx=buildStatusTransaction(new Account(key.publicKey(),'0'),manifest);const decoded=TransactionBuilder.fromXDR(tx.toXDR(),Networks.TESTNET);const operation=decoded.operations[0];assert.equal(operation.type,'manageData');assert.equal(operation.name,statusKey(manifest.id));assert.equal(operation.value.length,34);assert.equal(Buffer.from(operation.value).includes(Buffer.from(record.asset.serial_number)),false);assert.equal(Buffer.from(operation.value).includes(Buffer.from(manifest.salt,'hex')),false);assert.equal(decoded.networkPassphrase,Networks.TESTNET);});
test('transaction cannot use another issuer',()=>assert.throws(()=>buildStatusTransaction(new Account(Keypair.random().publicKey(),'0'),manifest),/issuer/));
test('status encoding rejects malformed and self-superseding entries',()=>{assert.throws(()=>decodeStatus(Buffer.alloc(64)));assert.throws(()=>encodeStatus(manifest,'superseded',manifest.id));assert.throws(()=>encodeStatus(manifest,'active','0'.repeat(32)));assert.throws(()=>encodeStatus(manifest,'other'));});
test('unsupported and non-JSON input fails before signing',()=>{assert.throws(()=>createAttestation({...record,schema_version:'9.9'},key));assert.throws(()=>createAttestation({...record,extra:NaN},key));assert.throws(()=>createAttestation({...record,extra:undefined},key));});
test('record is not changed by issuance',()=>{const before=structuredClone(record);createAttestation(record,key);assert.deepEqual(record,before);});

test('inherited property is not a status',()=>assert.throws(()=>encodeStatus(manifest,'toString'),/Unknown state/));
